# Generated by Django 2.1.7 on 2019-04-09 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='proudcts',
            new_name='products',
        ),
    ]
