# Generated by Django 2.1.7 on 2019-04-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartApp', '0002_auto_20190409_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
